version: '3'
services:
  viktoredmanse:
    build: .
    container_name: node_webserver
    command: node app.js
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - web
networks:
  web:
    external: true