version: '3'
services:
  viktoredmanse:
    image: node:current-alpine
    container_name: node_webserver
    command: node app.js
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - nginx-proxy-manager_default
    ports:
      - 30000:30000
networks:
  nginx-proxy-manager_default:
    external: true
